In [2]:
import math
import matplotlib.pyplot as plt
import keras
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import *
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping
df=pd.read_csv("TSLA.csv")
print('Number of rows and columns:', df.shape)
df.head(5)

Using TensorFlow backend.
C:\Users\silva\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\silva\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\silva\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\silva\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\silva\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\silva\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

Number of rows and columns: (1259, 7)

         Date       Open       High        Low      Close  Adj Close    Volume
0  2015-07-10  52.444000  52.599998  51.563999  51.830002  51.830002  13054500
1  2015-07-13  52.450001  52.509998  51.209999  52.431999  52.431999  14801500
2  2015-07-14  52.419998  53.198002  52.102001  53.130001  53.130001   9538000
3  2015-07-15  53.348000  53.498001  52.416000  52.627998  52.627998  10108000
4  2015-07-16  52.844002  53.439999  52.632000  53.335999  53.335999   8080000

In [3]:
df.tail(5)

,Date,Open,High,Low,Close,Adj Close,Volume
1254,2020-07-02,244.296005,245.600006,237.119995,241.731995,241.731995,86250500
1255,2020-07-06,255.337997,275.558014,253.207993,274.316010,274.316010,102849500
1256,2020-07-07,281.002014,285.899994,267.342010,277.971985,277.971985,107448500
1257,2020-07-08,281.000000,283.451996,262.268005,273.175995,273.175995,81556500
1258,2020-07-09,279.398010,281.712006,270.256012,278.855988,278.855988,58588000

In [4]:
training_set = df.iloc[:800, 1:2].values
test_set = df.iloc[800:, 1:2].values

In [5]:
training_set.shape

(800, 1)

In [6]:
training_set

array([[52.444   ],
       [52.450001],
       [52.419998],
       [53.348   ],
       [52.844002],
       [54.5     ],
       [55.      ],
       [54.009998],
       [52.254002],
       [53.93    ],
       [53.476002],
       [52.486   ],
       [51.150002],
       [52.854   ],
       [52.537998],
       [53.52    ],
       [53.257999],
       [52.001999],
       [52.716   ],
       [49.908001],
       [48.716   ],
       [47.630001],
       [47.43    ],
       [47.      ],
       [47.972   ],
       [49.448002],
       [51.112   ],
       [51.076   ],
       [52.066002],
       [50.411999],
       [47.200001],
       [40.557999],
       [46.104   ],
       [45.585999],
       [46.200001],
       [48.372002],
       [49.124001],
       [48.068001],
       [49.060001],
       [50.411999],
       [48.178001],
       [49.009998],
       [50.41    ],
       [49.445999],
       [49.528   ],
       [50.220001],
       [50.549999],
       [50.608002],
       [52.792   ],
       [51.591999],
       [52.796001],
       [51.806   ],
       [52.389999],
       [51.905998],
       [53.321999],
       [51.470001],
       [50.091999],
       [50.400002],
       [49.501999],
       [47.119999],
       [49.768002],
       [48.      ],
       [47.326   ],
       [46.015999],
       [44.186001],
       [44.598   ],
       [42.655998],
       [44.133999],
       [43.285999],
       [44.608002],
       [45.299999],
       [45.543999],
       [42.397999],
       [42.312   ],
       [43.      ],
       [42.276001],
       [42.967999],
       [42.262001],
       [42.349998],
       [42.080002],
       [41.784   ],
       [42.77    ],
       [45.400002],
       [46.116001],
       [46.139999],
       [46.598   ],
       [44.695999],
       [43.554001],
       [43.57    ],
       [42.59    ],
       [41.217999],
       [43.040001],
       [42.900002],
       [44.108002],
       [44.698002],
       [43.470001],
       [43.074001],
       [44.268002],
       [46.212002],
       [46.358002],
       [46.212002],
       [47.400002],
       [47.096001],
       [46.492001],
       [45.540001],
       [45.504002],
       [45.34    ],
       [44.942001],
       [45.048   ],
       [43.501999],
       [44.363998],
       [44.419998],
       [46.787998],
       [46.577999],
       [46.338001],
       [46.998001],
       [46.436001],
       [46.112   ],
       [46.298   ],
       [46.012001],
       [47.32    ],
       [47.702   ],
       [46.144001],
       [45.271999],
       [44.      ],
       [42.838001],
       [43.571999],
       [42.801998],
       [42.32    ],
       [42.402   ],
       [40.442001],
       [39.793999],
       [41.742001],
       [39.880001],
       [40.310001],
       [40.959999],
       [40.012001],
       [39.34    ],
       [38.476002],
       [38.158001],
       [37.990002],
       [37.751999],
       [38.484001],
       [36.717999],
       [34.139999],
       [34.259998],
       [31.42    ],
       [28.464001],
       [30.1     ],
       [30.4     ],
       [31.      ],
       [31.74    ],
       [31.799999],
       [34.484001],
       [32.731998],
       [34.023998],
       [35.231998],
       [34.549999],
       [35.73    ],
       [37.740002],
       [38.48    ],
       [38.849998],
       [36.745998],
       [37.655998],
       [39.599998],
       [39.535999],
       [40.700001],
       [40.903999],
       [42.      ],
       [41.585999],
       [42.529999],
       [42.854   ],
       [43.599998],
       [44.293999],
       [45.82    ],
       [47.068001],
       [47.442001],
       [46.473999],
       [43.155998],
       [46.321999],
       [45.978001],
       [47.018002],
       [45.868   ],
       [48.966   ],
       [49.824001],
       [48.099998],
       [50.793999],
       [53.290001],
       [52.099998],
       [50.200001],
       [49.900002],
       [49.702   ],
       [50.599998],
       [50.262001],
       [50.445999],
       [50.624001],
       [49.251999],
       [49.798   ],
       [49.778   ],
       [50.602001],
       [50.41    ],
       [50.549999],
       [49.970001],
       [49.627998],
       [48.299999],
       [47.472   ],
       [46.057999],
       [45.692001],
       [42.174   ],
       [43.144001],
       [41.509998],
       [41.518002],
       [42.287998],
       [41.556   ],
       [41.630001],
       [41.810001],
       [41.830002],
       [42.723999],
       [43.397999],
       [43.973999],
       [43.32    ],
       [43.582001],
       [44.099998],
       [44.998001],
       [44.608002],
       [44.296001],
       [43.917999],
       [44.      ],
       [43.599998],
       [44.448002],
       [46.759998],
       [46.995998],
       [45.478001],
       [43.900002],
       [43.776001],
       [43.389999],
       [43.484001],
       [43.562   ],
       [43.900002],
       [44.136002],
       [39.894001],
       [39.138   ],
       [38.009998],
       [38.172001],
       [40.377998],
       [41.026001],
       [42.594002],
       [41.228001],
       [41.945999],
       [42.      ],
       [42.619999],
       [43.560001],
       [43.992001],
       [44.82    ],
       [45.099998],
       [44.624001],
       [44.504002],
       [43.928001],
       [45.      ],
       [45.293999],
       [45.200001],
       [44.397999],
       [44.453999],
       [45.537998],
       [45.868   ],
       [45.59    ],
       [46.139999],
       [47.099998],
       [45.874001],
       [45.473999],
       [45.138   ],
       [46.      ],
       [45.599998],
       [45.363998],
       [45.647999],
       [45.234001],
       [45.082001],
       [45.203999],
       [45.098   ],
       [44.866001],
       [44.764   ],
       [44.708   ],
       [44.834   ],
       [44.863998],
       [45.41    ],
       [44.622002],
       [44.428001],
       [44.029999],
       [43.222   ],
       [42.085999],
       [41.801998],
       [40.466   ],
       [39.804001],
       [41.099998],
       [39.91    ],
       [39.818001],
       [39.      ],
       [39.411999],
       [39.150002],
       [39.298   ],
       [40.084   ],
       [41.400002],
       [41.369999],
       [41.273998],
       [41.279999],
       [41.198002],
       [41.299999],
       [41.93    ],
       [41.501999],
       [41.119999],
       [40.442001],
       [42.459999],
       [42.619999],
       [42.448002],
       [40.492001],
       [40.200001],
       [40.27    ],
       [40.369999],
       [40.189999],
       [40.099998],
       [40.132   ],
       [39.41    ],
       [39.198002],
       [39.948002],
       [40.424   ],
       [39.720001],
       [40.200001],
       [40.580002],
       [40.200001],
       [42.268002],
       [40.799999],
       [40.498001],
       [39.608002],
       [38.009998],
       [37.799999],
       [37.799999],
       [38.717999],
       [38.757999],
       [37.375999],
       [38.209999],
       [36.848   ],
       [37.599998],
       [36.556   ],
       [36.529999],
       [36.698002],
       [38.130001],
       [37.007999],
       [37.167999],
       [38.122002],
       [38.728001],
       [39.096001],
       [39.112   ],
       [38.200001],
       [37.650002],
       [36.576   ],
       [36.501999],
       [37.104   ],
       [37.23    ],
       [38.41    ],
       [38.174   ],
       [38.560001],
       [38.636002],
       [39.748001],
       [39.681999],
       [39.616001],
       [40.498001],
       [40.610001],
       [41.689999],
       [41.644001],
       [41.599998],
       [42.976002],
       [44.306   ],
       [43.712002],
       [43.259998],
       [42.972   ],
       [42.950001],
       [45.284   ],
       [45.386002],
       [45.793999],
       [46.400002],
       [45.813999],
       [45.812   ],
       [46.      ],
       [47.34    ],
       [47.330002],
       [49.450001],
       [49.091999],
       [49.169998],
       [50.      ],
       [51.462002],
       [50.858002],
       [50.276001],
       [50.506001],
       [49.848   ],
       [50.610001],
       [49.667999],
       [50.382   ],
       [50.200001],
       [51.638   ],
       [51.470001],
       [53.25    ],
       [53.958   ],
       [54.147999],
       [55.806   ],
       [56.      ],
       [55.52    ],
       [53.16    ],
       [55.09    ],
       [56.062   ],
       [52.799999],
       [50.532001],
       [49.633999],
       [48.838001],
       [50.835999],
       [49.942001],
       [50.147999],
       [49.582001],
       [50.383999],
       [49.400002],
       [49.526001],
       [49.242001],
       [48.964001],
       [49.222   ],
       [51.400002],
       [52.48    ],
       [52.799999],
       [52.119999],
       [52.566002],
       [50.312   ],
       [51.077999],
       [51.139999],
       [52.119999],
       [55.403999],
       [55.667999],
       [55.608002],
       [55.745998],
       [57.380001],
       [59.377998],
       [60.408001],
       [59.375999],
       [59.5     ],
       [61.830002],
       [62.675999],
       [61.268002],
       [59.34    ],
       [60.540001],
       [59.939999],
       [60.492001],
       [61.301998],
       [60.400002],
       [61.844002],
       [61.599998],
       [62.473999],
       [62.338001],
       [61.966   ],
       [62.976002],
       [64.800003],
       [63.534   ],
       [61.487999],
       [59.599998],
       [62.18    ],
       [61.875999],
       [64.311996],
       [64.68    ],
       [65.096001],
       [63.675999],
       [63.518002],
       [62.877998],
       [61.400002],
       [63.099998],
       [62.560001],
       [62.091999],
       [61.301998],
       [62.203999],
       [63.456001],
       [65.199997],
       [67.538002],
       [68.800003],
       [67.954002],
       [67.699997],
       [68.940002],
       [71.267998],
       [72.75    ],
       [74.884003],
       [71.598   ],
       [73.524002],
       [76.218002],
       [74.5     ],
       [75.596001],
       [75.      ],
       [75.334   ],
       [74.870003],
       [75.598   ],
       [76.489998],
       [77.337997],
       [75.279999],
       [73.335999],
       [74.122002],
       [72.741997],
       [74.047997],
       [69.440002],
       [63.452   ],
       [62.700001],
       [62.580002],
       [63.200001],
       [66.080002],
       [66.022003],
       [64.638   ],
       [65.108002],
       [63.5     ],
       [65.646004],
       [65.379997],
       [65.891998],
       [66.047997],
       [69.      ],
       [68.071999],
       [69.199997],
       [67.377998],
       [67.099998],
       [64.599998],
       [63.787998],
       [69.066002],
       [69.400002],
       [71.470001],
       [71.505997],
       [72.199997],
       [72.32    ],
       [71.393997],
       [72.926003],
       [73.040001],
       [72.599998],
       [72.241997],
       [70.582001],
       [69.164001],
       [68.225998],
       [67.797997],
       [70.503998],
       [70.848   ],
       [69.456001],
       [67.896004],
       [69.933998],
       [70.709999],
       [71.223999],
       [70.760002],
       [69.900002],
       [69.195999],
       [69.797997],
       [70.269997],
       [72.898003],
       [72.764   ],
       [72.865997],
       [74.902   ],
       [76.050003],
       [76.      ],
       [74.599998],
       [74.980003],
       [73.297997],
       [70.629997],
       [70.185997],
       [69.980003],
       [67.975998],
       [68.372002],
       [68.503998],
       [67.18    ],
       [70.25    ],
       [71.199997],
       [70.620003],
       [69.93    ],
       [69.360001],
       [70.778   ],
       [70.589996],
       [71.396004],
       [70.751999],
       [70.181999],
       [71.194   ],
       [71.112   ],
       [70.538002],
       [69.975998],
       [67.760002],
       [67.339996],
       [65.556   ],
       [63.950001],
       [63.835999],
       [64.045998],
       [66.449997],
       [60.026001],
       [59.900002],
       [61.400002],
       [60.203999],
       [61.099998],
       [60.5     ],
       [60.5     ],
       [60.026001],
       [63.      ],
       [61.202   ],
       [62.798   ],
       [65.134003],
       [62.757999],
       [62.172001],
       [63.354   ],
       [62.757999],
       [62.650002],
       [63.271999],
       [63.459999],
       [61.712002],
       [61.088001],
       [61.299999],
       [60.400002],
       [60.02    ],
       [62.400002],
       [62.919998],
       [62.925999],
       [66.089996],
       [68.185997],
       [68.202003],
       [68.407997],
       [68.980003],
       [68.052002],
       [66.538002],
       [65.917999],
       [65.902   ],
       [64.765999],
       [63.200001],
       [62.349998],
       [63.236   ],
       [62.400002],
       [64.199997],
       [62.574001],
       [63.324001],
       [63.200001],
       [67.031998],
       [66.440002],
       [67.047997],
       [67.725998],
       [67.508003],
       [68.094002],
       [69.134003],
       [69.      ],
       [69.879997],
       [72.      ],
       [70.916   ],
       [69.653999],
       [68.300003],
       [67.970001],
       [69.028   ],
       [69.501999],
       [70.199997],
       [69.688004],
       [67.594002],
       [65.042   ],
       [67.797997],
       [68.662003],
       [63.986   ],
       [63.226002],
       [63.004002],
       [64.167999],
       [64.900002],
       [66.5     ],
       [66.893997],
       [67.206001],
       [67.106003],
       [69.566002],
       [70.699997],
       [71.25    ],
       [70.514   ],
       [69.001999],
       [65.396004],
       [66.477997],
       [66.75    ],
       [65.087997],
       [66.571999],
       [64.82    ],
       [65.722   ],
       [65.722   ],
       [67.351997],
       [65.875999],
       [64.585999],
       [63.299999],
       [62.973999],
       [62.049999],
       [62.778   ],
       [62.25    ],
       [61.467999],
       [60.799999],
       [52.916   ],
       [51.298   ],
       [51.251999],
       [53.964001],
       [50.556   ],
       [57.868   ],
       [60.200001],
       [60.074001],
       [59.793999],
       [60.147999],
       [60.464001],
       [60.720001],
       [59.799999],
       [57.773998],
       [58.216   ],
       [58.216   ],
       [59.034   ],
       [58.257999],
       [57.      ],
       [56.700001],
       [55.75    ],
       [57.074001],
       [58.722   ],
       [58.702   ],
       [59.714001],
       [55.757999],
       [56.599998],
       [59.5     ],
       [60.16    ],
       [60.082001],
       [61.5     ],
       [61.540001],
       [60.664001],
       [57.001999],
       [56.765999],
       [57.18    ],
       [56.93    ],
       [56.265999],
       [57.551998],
       [55.551998],
       [55.68    ],
       [55.526001],
       [55.702   ],
       [56.658001],
       [57.442001],
       [57.172001],
       [58.868   ],
       [59.540001],
       [60.099998],
       [63.23    ],
       [63.799999],
       [64.501999],
       [68.940002],
       [69.342003],
       [69.526001],
       [70.767998],
       [71.080002],
       [73.031998],
       [71.608002],
       [72.400002],
       [70.307999],
       [66.024002],
       [67.209999],
       [69.      ],
       [69.732002],
       [70.666   ],
       [72.014   ],
       [66.349998],
       [62.751999],
       [60.990002],
       [62.397999],
       [64.912003],
       [63.16    ],
       [64.286003],
       [63.116001],
       [62.341999],
       [61.762001],
       [65.      ],
       [63.265999],
       [64.246002],
       [60.368   ],
       [60.883999],
       [59.348   ],
       [60.970001],
       [61.450001],
       [59.18    ],
       [58.450001],
       [59.598   ],
       [65.688004],
       [69.561996],
       [69.092003],
       [68.767998],
       [73.818001],
       [73.110001],
       [70.800003],
       [72.225998],
       [71.690002],
       [68.382004],
       [67.982002],
       [64.699997],
       [58.34    ],
       [62.122002],
       [64.174004],
       [63.827999],
       [64.139999],
       [63.599998],
       [63.681999],
       [62.054001],
       [60.452   ],
       [60.400002],
       [59.388   ],
       [57.009998],
       [56.959999],
       [52.02    ],
       [54.652   ],
       [55.894001]])

In [11]:
dataset_train = df.iloc[:800, 1:2]
dataset_test = df.iloc[800:, 1:2]
dataset_total = pd.concat((dataset_train, dataset_test), axis = 0)
inputs = dataset_total[len(dataset_total) - len(dataset_test) - 60:].values

In [10]:
test_set.shape

(459, 1)

In [13]:
inputs.shape

(519, 1)