## This notebook inputs the missing values using Missing Indicators

In [1]:
import pandas as pd
from datetime import datetime
import numpy as np
from sklearn.impute import MissingIndicator

#### Choose wether the imputation should be done on the data set with daily or weekly granularity

In [2]:
INPUT, OUTPUT = 'output/\CompleteDengue', 'output/\MIIDengueImputed'

In [3]:
df = pd.read_csv(r'output\/CompleteDengue.csv',index_col=0)
df_train = df.loc['1990-04-30':'2004-06-03'].dropna(how='all', axis=1) #Selecting training data
df_test = df.loc['2004-06-10':, df_train.columns] #Selecting test data
df = df_train

In [4]:
indicator = MissingIndicator(missing_values=np.nan, features="all")

In [5]:
indicator.fit(df)
mask_all = indicator.transform(df)
mask_test_all = indicator.transform(df_test)

In [6]:
df_masks = pd.DataFrame(data=mask_all, index=df.index, columns=df.columns)
df_test_masks = pd.DataFrame(data=mask_test_all, index=df_test.index, columns=df_test.columns)

In [7]:
df_masks = df_masks.add_prefix('MI_')
df_test_masks = df_test_masks.add_prefix('MI_')

In [8]:
df_final = pd.concat([df, df_masks], axis=1, join='outer')
df_test_final = pd.concat([df_test, df_test_masks], axis=1, join='outer')

In [9]:
df_final.head()

,sj_ndvi_ne,sj_ndvi_nw,sj_ndvi_se,sj_ndvi_sw,sj_precipitation_amt_mm,sj_reanalysis_air_temp_k,sj_reanalysis_avg_temp_k,sj_reanalysis_dew_point_temp_k,sj_reanalysis_max_air_temp_k,sj_reanalysis_min_air_temp_k,...,MI_iq_reanalysis_precip_amt_kg_per_m2,MI_iq_reanalysis_relative_humidity_percent,MI_iq_reanalysis_sat_precip_amt_mm,MI_iq_reanalysis_specific_humidity_g_per_kg,MI_iq_reanalysis_tdtr_k,MI_iq_station_avg_temp_c,MI_iq_station_diur_temp_rng_c,MI_iq_station_max_temp_c,MI_iq_station_min_temp_c,MI_iq_station_precip_mm
1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,297.742857,292.414286,299.8,295.9,...,True,True,True,True,True,True,True,True,True,True
1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,298.442857,293.951429,300.9,296.4,...,True,True,True,True,True,True,True,True,True,True
1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,298.878571,295.434286,300.5,297.3,...,True,True,True,True,True,True,True,True,True,True
1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,299.228571,295.310000,301.4,297.0,...,True,True,True,True,True,True,True,True,True,True
1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,299.664286,295.821429,301.9,297.5,...,True,True,True,True,True,True,True,True,True,True

In [10]:
df.head()

,sj_ndvi_ne,sj_ndvi_nw,sj_ndvi_se,sj_ndvi_sw,sj_precipitation_amt_mm,sj_reanalysis_air_temp_k,sj_reanalysis_avg_temp_k,sj_reanalysis_dew_point_temp_k,sj_reanalysis_max_air_temp_k,sj_reanalysis_min_air_temp_k,...,iq_reanalysis_precip_amt_kg_per_m2,iq_reanalysis_relative_humidity_percent,iq_reanalysis_sat_precip_amt_mm,iq_reanalysis_specific_humidity_g_per_kg,iq_reanalysis_tdtr_k,iq_station_avg_temp_c,iq_station_diur_temp_rng_c,iq_station_max_temp_c,iq_station_min_temp_c,iq_station_precip_mm
1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,297.742857,292.414286,299.8,295.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,298.442857,293.951429,300.9,296.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,298.878571,295.434286,300.5,297.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,299.228571,295.310000,301.4,297.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,299.664286,295.821429,301.9,297.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_final=df_final.fillna(0)
df_test_final=df_test_final.fillna(0)
df_final.head()

,sj_ndvi_ne,sj_ndvi_nw,sj_ndvi_se,sj_ndvi_sw,sj_precipitation_amt_mm,sj_reanalysis_air_temp_k,sj_reanalysis_avg_temp_k,sj_reanalysis_dew_point_temp_k,sj_reanalysis_max_air_temp_k,sj_reanalysis_min_air_temp_k,...,MI_iq_reanalysis_precip_amt_kg_per_m2,MI_iq_reanalysis_relative_humidity_percent,MI_iq_reanalysis_sat_precip_amt_mm,MI_iq_reanalysis_specific_humidity_g_per_kg,MI_iq_reanalysis_tdtr_k,MI_iq_station_avg_temp_c,MI_iq_station_diur_temp_rng_c,MI_iq_station_max_temp_c,MI_iq_station_min_temp_c,MI_iq_station_precip_mm
1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,297.742857,292.414286,299.8,295.9,...,True,True,True,True,True,True,True,True,True,True
1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,298.442857,293.951429,300.9,296.4,...,True,True,True,True,True,True,True,True,True,True
1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,298.878571,295.434286,300.5,297.3,...,True,True,True,True,True,True,True,True,True,True
1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,299.228571,295.310000,301.4,297.0,...,True,True,True,True,True,True,True,True,True,True
1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,299.664286,295.821429,301.9,297.5,...,True,True,True,True,True,True,True,True,True,True

In [12]:
df_final.to_csv(OUTPUT+'_training.csv', index = True)
df_test_final.to_csv(OUTPUT+ '_test.csv', index = True)