## This notebook inputs the missing values using Mean Imputation

In [1]:
import pandas as pd
from datetime import datetime
import numpy as np
from sklearn.impute import SimpleImputer

#### Choose wether the imputation should be done on the data set with daily or weekly granularity

In [2]:
INPUT, OUTPUT = 'output/CompleteDengue.csv', 'output/\MeanDengueImputed'

In [3]:
df = pd.read_csv(r'output\/CompleteDengue.csv',index_col=0)
df_train = df.loc['1990-04-30':'2006-07-16'].dropna(how='all', axis=1) #Selecting training data
df_test = df.loc['2006-07-23':, df_train.columns] #Selecting test data
df = df_train

In [4]:
df.tail()

,sj_ndvi_ne,sj_ndvi_nw,sj_ndvi_se,sj_ndvi_sw,sj_precipitation_amt_mm,sj_reanalysis_air_temp_k,sj_reanalysis_avg_temp_k,sj_reanalysis_dew_point_temp_k,sj_reanalysis_max_air_temp_k,sj_reanalysis_min_air_temp_k,...,iq_reanalysis_precip_amt_kg_per_m2,iq_reanalysis_relative_humidity_percent,iq_reanalysis_sat_precip_amt_mm,iq_reanalysis_specific_humidity_g_per_kg,iq_reanalysis_tdtr_k,iq_station_avg_temp_c,iq_station_diur_temp_rng_c,iq_station_max_temp_c,iq_station_min_temp_c,iq_station_precip_mm
2006-06-18,-0.010033,-0.057200,0.151700,0.149883,7.56,301.021429,301.142857,296.361429,303.3,299.6,...,21.50,87.214286,84.99,16.258571,10.071429,28.10,12.70,34.4,21.4,79.5
2006-06-25,0.025500,0.042767,0.107043,0.110557,19.95,300.478571,300.535714,296.642857,302.4,298.7,...,27.29,88.471429,71.69,15.801429,10.785714,26.60,10.35,32.5,20.4,74.9
2006-07-02,0.103500,0.197700,0.133871,0.122943,111.15,300.504286,300.635714,297.161429,303.0,299.0,...,9.16,83.467143,17.21,15.020000,10.742857,27.20,10.30,33.4,19.8,21.9
2006-07-09,0.063875,0.054850,0.177033,0.133333,52.63,300.584286,300.607143,296.518571,302.4,298.8,...,13.62,90.432857,20.72,16.005714,7.971429,26.70,9.40,33.0,21.7,110.6
2006-07-16,0.019300,0.069233,0.123271,0.105829,56.73,300.262857,300.428571,296.780000,303.0,298.4,...,1.80,77.271429,1.17,14.417143,11.428571,26.25,10.40,33.1,20.6,0.5

In [5]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(df)

SimpleImputer()

In [6]:
df_imputed = imp.transform(df)
df_test_imputed = imp.transform(df_test)

In [7]:
df_final = pd.DataFrame(data=df_imputed, index=df.index, columns=df.columns)
df_test_final = pd.DataFrame(data=df_test_imputed, index=df_test.index, columns=df_test.columns)

In [8]:
df_final.head()

,sj_ndvi_ne,sj_ndvi_nw,sj_ndvi_se,sj_ndvi_sw,sj_precipitation_amt_mm,sj_reanalysis_air_temp_k,sj_reanalysis_avg_temp_k,sj_reanalysis_dew_point_temp_k,sj_reanalysis_max_air_temp_k,sj_reanalysis_min_air_temp_k,...,iq_reanalysis_precip_amt_kg_per_m2,iq_reanalysis_relative_humidity_percent,iq_reanalysis_sat_precip_amt_mm,iq_reanalysis_specific_humidity_g_per_kg,iq_reanalysis_tdtr_k,iq_station_avg_temp_c,iq_station_diur_temp_rng_c,iq_station_max_temp_c,iq_station_min_temp_c,iq_station_precip_mm
1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,297.742857,292.414286,299.8,295.9,...,52.260607,87.628658,62.473099,16.842492,9.477088,27.507751,10.568408,33.954693,21.2,66.254045
1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,298.442857,293.951429,300.9,296.4,...,52.260607,87.628658,62.473099,16.842492,9.477088,27.507751,10.568408,33.954693,21.2,66.254045
1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,298.878571,295.434286,300.5,297.3,...,52.260607,87.628658,62.473099,16.842492,9.477088,27.507751,10.568408,33.954693,21.2,66.254045
1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,299.228571,295.310000,301.4,297.0,...,52.260607,87.628658,62.473099,16.842492,9.477088,27.507751,10.568408,33.954693,21.2,66.254045
1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,299.664286,295.821429,301.9,297.5,...,52.260607,87.628658,62.473099,16.842492,9.477088,27.507751,10.568408,33.954693,21.2,66.254045

In [9]:
df_final.to_csv(OUTPUT+'_training.csv', index = True)
df_test_final.to_csv(OUTPUT+ '_test.csv', index = True)

In [10]:
df_imputed.shape

(844, 40)