## This notebook inputs the missing values using Mean Imputation

In [1]:
import pandas as pd
from datetime import datetime
import numpy as np
from sklearn.impute import SimpleImputer

#### Choose wether the imputation should be done on the data set with daily or weekly granularity

In [2]:
INPUT, OUTPUT = 'output/\CompleteCovid', 'output/\MeanCovidImputed'

In [3]:
df = pd.read_csv(r'output\/CompleteCovid.csv',index_col=0)
df_train = df.loc['2020-01-22 09:00:00':'2020-02-26 02:00:00'].dropna(how='all', axis=1) #Selecting training data
df_test = df.loc['2020-02-26 02:30:00':, df_train.columns] #Selecting test data
df = df_train

In [4]:
df.tail()

,Asia_confirmed_cases,Asia_deaths,Asia_recovered,Europe_confirmed_cases,Europe_deaths,Europe_recovered,Americas_confirmed_cases,Americas_deaths,Americas_recovered,Oceania_confirmed_cases,Oceania_deaths,Oceania_recovered,Africa_confirmed_cases,Africa_deaths,Africa_recovered
update_time,,,,,,,,,,,,,,,
2020-02-26 00:00:00,121.0,1.0,88.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-02-26 00:30:00,400.0,4.0,235.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-02-26 01:00:00,934.0,1.0,719.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-02-26 01:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-02-26 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(df)

SimpleImputer()

In [6]:
df_imputed = imp.transform(df)
df_test_imputed = imp.transform(df_test)

In [7]:
df_final = pd.DataFrame(data=df_imputed, index=df.index, columns=df.columns)
df_test_final = pd.DataFrame(data=df_test_imputed, index=df_test.index, columns=df_test.columns)

In [8]:
df_final.head()

,Asia_confirmed_cases,Asia_deaths,Asia_recovered,Europe_confirmed_cases,Europe_deaths,Europe_recovered,Americas_confirmed_cases,Americas_deaths,Americas_recovered,Oceania_confirmed_cases,Oceania_deaths,Oceania_recovered,Africa_confirmed_cases,Africa_deaths,Africa_recovered
update_time,,,,,,,,,,,,,,,
2020-01-22 09:00:00,270.000000,6.000000,0.000000,30.361111,0.694444,2.361111,6.159091,0.0,0.272727,6.647059,0.0,0.529412,1.0,0.0,0.0
2020-01-22 09:30:00,2260.259178,60.410111,315.506993,30.361111,0.694444,2.361111,6.159091,0.0,0.272727,6.647059,0.0,0.529412,1.0,0.0,0.0
2020-01-22 10:00:00,2260.259178,60.410111,315.506993,30.361111,0.694444,2.361111,6.159091,0.0,0.272727,6.647059,0.0,0.529412,1.0,0.0,0.0
2020-01-22 10:30:00,2260.259178,60.410111,315.506993,30.361111,0.694444,2.361111,6.159091,0.0,0.272727,6.647059,0.0,0.529412,1.0,0.0,0.0
2020-01-22 11:00:00,2260.259178,60.410111,315.506993,30.361111,0.694444,2.361111,6.159091,0.0,0.272727,6.647059,0.0,0.529412,1.0,0.0,0.0

In [9]:
df_final.to_csv(OUTPUT+'_training.csv', index = True)
df_test_final.to_csv(OUTPUT+ '_test.csv', index = True)

In [10]:
df_imputed.shape

(1667, 15)